### ISSUE TITLE
Global result "OK" while one sensor result is "CRITICAL"

### ISSUE THREAD

**Issue by henningkessler** [NETWAYS/check_akcp_sensorprobe#1]
Hello,

I just implemented this check into my new icinga installation and was surprised that the global result of this check was "OK" while one of the sensor results (Motion Sensor) was "CRITICAL". Any Ideas why this can happen?
![globalresult](https://user-images.githubusercontent.com/2575649/42035933-63980330-7ae4-11e8-8795-b45825dd7a04.png)

**Comment by martialblog** [comment]
The device is in EOL. This Repository will be archived
