### ISSUE TITLE
Critical Alert although all Sensors are ok

### ISSUE THREAD

**Issue by MarcusCaepio** [NETWAYS/check_akcp_sensorprobe#2]
Hi Michi, 
we got a strange behavior with the plugin.
Although all Sensors are ok, the plugin gives us a critical value.
Output is:
```
CRITICAL sensorProbe2 PoE v2.0: Sensor reports one or more critical issues
OK Temperature sensor "Temperature": 24.90C (15.0:27.0/5.0:28.0)
OK Humidity sensor "Humidity": 40.00% (8.0:90.0/5.0:95.0)

```
Any Idea what the reason could be?
Cheers,
Marcus

**Comment by mxhash** [comment]
Hi,

looks like that this could be a "global" issue. Does the device report any issues?

What happens if you test the plugin in verbose mode?

Cheers,
Marius

**Comment by MarcusCaepio** [comment]
Not really. At least I couldn't find sth. in the webgui. After a hard reboot, it was ok again. Any idea, what coould trigger a global problem?

**Comment by mxhash** [comment]
No not really. Just saw in the code that a "global" status was fetched before the sensors were queried. And to be honest the "verbose" does exactly nothing. Just saw it ;-)

**Comment by martialblog** [comment]
The device is in EOL. This Repository will be archived
